### ISSUE TITLE
Ajout d'un lien vers la page wikipédia des personnalités

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [RaitoBezarius/unionGov#12]
Ou à défaut vers le site de la personne.
Je verrai bien un petit icône wikipédia à la suite du nom
Et un icône lien si c'est en dehors de wikipédia

**Comment by Jacques-Olivier-Farcy** [comment]
https://iconarchive.com/show/popular-sites-icons-by-sykonist/Wikipedia-icon.html

**Comment by RaitoBezarius** [comment]
Implémenté dans https://github.com/RaitoBezarius/unionGov/commit/c367207e952423c41221f75378fd32587dd5f8b8
