### ISSUE TITLE
Le lien de partage ne redonne pas les choix des personnalités

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [RaitoBezarius/unionGov#15]
Par exemple : https://gouv.charlotte-marchandise.fr/212

**Comment by Jacques-Olivier-Farcy** [comment]
![image](https://user-images.githubusercontent.com/19731340/146991077-fc6947e9-56c1-4ce6-a65f-b4cd60ff6dfe.png)

**Comment by RaitoBezarius** [comment]
@Jacques-Olivier-Farcy c'est fixé, si tu veux bien me confirmer ; je ferme en attendant, n'hésite pas à réouvrir si tu reconstates le bug.

Pour référence : le pré-rendu des pages a échoué à cause d'un changement de sécurité dans le backend temporaire et n'a pas été retenté, ce qui a cassé tous les rendus de pages de partage.
