### ISSUE TITLE
Simple GitHub Action CI?

### ISSUE THREAD

**Issue by yvan-sraka** [RaitoBezarius/unionGov#18]

**Comment by RaitoBezarius** [comment]
Tu vois quoi pour la GH Action, @yvan-sraka ? Un Nix build de tout le tralala que j'utilise pour le déploiement? Des tests?

Sur le moyen terme, je pourrais faire un truc de type: construire la tarball finale et l'envoyer sur la prod, mais comme Next.js fait du pre-(server side rendering) pour pré-rendre toutes les pages de gouvernements générés, c'est chiant à nixifier parce que ça viole la condition de sandboxing réseau, du coup, c'est un pre-start de l'unité systemd du runtime Next.js ; ce qui rend long les déploiements et ne permet pas de faire du zero downtime hélas.

Une autre solution serait de découper en 2 unités systemd, le générateur du bundle, appelé lorsqu'une condition change, une fois que celui ci atteint la complétion, il restart le runtime Next.js, ce qui a le bon goût de faire du ~zero downtime modulo sd_notify.

**Comment by RaitoBezarius** [comment]
Le code de déploiement est sur ma machine, mais il contient l'état NixOps qui est "un tout petit peu" sensible, donc je vais devoir git-crypt le fichier.

**Comment by RaitoBezarius** [comment]
Bon, fait dans https://github.com/RaitoBezarius/unionGov/commit/d0a09baac48b3b312cb1a0c39f3e4532a46964db

**Comment by yvan-sraka** [comment]
> Bon, fait dans [d0a09ba](https://github.com/RaitoBezarius/unionGov/commit/d0a09baac48b3b312cb1a0c39f3e4532a46964db)

Il manque le GitHub Action `.yml` qui va bien non ?
