### ISSUE TITLE
Faire un collage pour l'aperçu?

### ISSUE THREAD

**Issue by RaitoBezarius** [RaitoBezarius/unionGov#2]
En partant de quelque chose comme ça et en superposant les têtes des personnalités ; on peut faire un truc côté Django dynamiquement.

![image](https://user-images.githubusercontent.com/314564/146748121-cf70dd82-305d-49fc-be0b-04f7797852d5.png)

**Comment by Jacques-Olivier-Farcy** [comment]
Utiliser plutôt si possible des "trous" hexagonaux

**Comment by Jacques-Olivier-Farcy** [comment]
![hexa](https://user-images.githubusercontent.com/19731340/146748899-db68af7e-2cf6-4693-bbaf-753fb502adbb.png)

**Comment by Jacques-Olivier-Farcy** [comment]
![hexa-sombre](https://user-images.githubusercontent.com/19731340/146749626-11ff957f-bef7-4013-871f-264d1ca4ddc8.png)

**Comment by RaitoBezarius** [comment]
@yvan-sraka tu penses que tu pourrais faire le collage avec `PIL` en Python ou en appelant `convert` (ImageMagick), puis mettre ça en cache au niveau d'une vue Django au niveau de là: https://github.com/RaitoBezarius/unionGov/blob/develop/unionGov/gov/views.py#L87-L90

**Comment by RaitoBezarius** [comment]
Devrait être fixé par #17
