### ISSUE TITLE
Lien de partage d'un gouvernement déjà partagé ne fonctionne pas

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [RaitoBezarius/unionGov#21]
Est-ce qu'il serait possible de remettre le bouton partager sur un gouvernement existant ?

**Comment by RaitoBezarius** [comment]
Ah pardon, oui je peux, mais l'effet de ce bouton c'est de redonner le lien de partage ?

**Comment by Jacques-Olivier-Farcy** [comment]
Oui l'idée c'est que quelqu'un puisse repartager un gouvernement déjà construit

**Comment by RaitoBezarius** [comment]
Mais est ce que je comptabilise ça comme un gouvernement nouvellement crée @Jacques-Olivier-Farcy ?

**Comment by Jacques-Olivier-Farcy** [comment]
Non
