### ISSUE TITLE
Changement de photo d'une personnalité

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [RaitoBezarius/unionGov#31]
Ce que je fais :
1 Je coche clear pour la personnalité
2 Je clique sur SAVE

Je me retrouve avec un message d'erreur :

![image](https://user-images.githubusercontent.com/19731340/147770609-02cf1c5d-9827-477e-ba58-08aff9f68574.png)

**Comment by RaitoBezarius** [comment]
Closed in https://github.com/RaitoBezarius/unionGov/commit/79ec0b98313b9af1f3fc03b35da67ff006a67093
