### ISSUE TITLE
Superposer un cadre pour les photos de personnalités

### ISSUE THREAD

**Issue by RaitoBezarius** [RaitoBezarius/unionGov#8]

**Comment by RaitoBezarius** [comment]
![image](https://user-images.githubusercontent.com/314564/146748696-af7a741c-c6e0-4305-a3cd-4950d0b7c161.png)

**Comment by yvan-sraka** [comment]
![146748696-af7a741c-c6e0-4305-a3cd-4950d0b7c161](https://user-images.githubusercontent.com/705213/146987605-c577bc6c-e889-4b7d-8572-dcec61aa6499.png)
